export const leads = [
  {
    id: 1,
    name: "Jane Doe",
    service: "Web Development",
    location: "New York, USA",
    budget: "$2,000",
    jobDescription: "Build a responsive website for an e-commerce store.",
    selected: true,
    responses: 2,
    price: 33,
    phone: "077*******",
    email: "J**********@gmail.com",
  },
  {
    id: 2,
    name: "John Smith",
    service: "Graphic Design",
    location: "Los Angeles, USA",
    budget: "$1,500",
    jobDescription: "Create a modern and eye-catching logo for a startup.",
    responses: 4,
    price: 33,
    phone: "079*******",
    email: "J**********@gmail.com",
  },
  {
    id: 3,
    name: "Alice Johnson",
    service: "Social Media Marketing",
    location: "London, UK",
    budget: "$800",
    jobDescription:
      "Run a targeted social media campaign for a small business.",
    responses: 1,
    price: 33,
    phone: "077*******",
    email: "A**********@gmail.com",
  },
  {
    id: 4,
    name: "Bob Williams",
    service: "Mobile App Development",
    location: "Toronto, Canada",
    budget: "$3,500",
    jobDescription:
      "Develop a cross-platform mobile app for a fitness tracking service.",
    responses: 0,
    price: 33,
    phone: "097*******",
    email: "B**********@gmail.com",
  },
];
